development:
  adapter: postgresql
  database: prelaunchr_development
  host: localhost
test:
  adapter: postgresql
  database: prelaunchr_test
  host: localhost

production:
  url: <%= ENV['ec2-54-221-246-85.compute-1.amazonaws.com'] %>
